### ISSUE TITLE
terminal output panics when using temp pipe file

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras#1167]
### What happened in your environment?

When I run below command in bash, I got unexpected panic

```console
$ oras-main push --artifact-type my.test/example --config <(echo 123):bar/test localhost:5000/test:config foo

panic: strings: negative Repeat count

goroutine 9 [running]:
strings.Repeat({0x98e380?, 0x12?}, 0xc0002d7df8?)
        /home/azureuser/bin/go/src/strings/strings.go:554 +0x318
oras.land/oras/cmd/oras/internal/display/progress.(*status).String(0xc0000b58c0, 0x78)
        /home/azureuser/go/pkg/mod/oras.land/oras@v1.1.1-0.20231027102508-9ec4f1b2845e/cmd/oras/internal/display/progress/status.go:128 +0x452
oras.land/oras/cmd/oras/internal/display/progress.(*manager).render(0xc000076cc0)
        /home/azureuser/go/pkg/mod/oras.land/oras@v1.1.1-0.20231027102508-9ec4f1b2845e/cmd/oras/internal/display/progress/manager.go:100 +0xcd
oras.land/oras/cmd/oras/internal/display/progress.(*manager).start.func1()
        /home/azureuser/go/pkg/mod/oras.land/oras@v1.1.1-0.20231027102508-9ec4f1b2845e/cmd/oras/internal/display/progress/manager.go:77 +0xf6
created by oras.land/oras/cmd/oras/internal/display/progress.(*manager).start in goroutine 1
        /home/azureuser/go/pkg/mod/oras.land/oras@v1.1.1-0.20231027102508-9ec4f1b2845e/cmd/oras/internal/display/progress/manager.go:71 +0x7c
```

### What did you expect to happen?

Should output proper error message rather than panic.

### How can we reproduce it?

Try below command with bash
> oras push --artifact-type my.test/example --config <(echo 123):bar/test localhost:5000/test:config foo

### What is the version of your ORAS CLI?

Version:    1.1.0+unreleased
Go version: go1.21.0

### What is your OS environment?

Ubuntu 20.04

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by qweeah** [comment]
This issue is already fixed by #1178
